export interface SchoolResponse {
  id: string;
  name: string;
  address: string;
  phoneNumber: string;
  courses: string[];
  principal: string;
  website: string | null;
  isActive: boolean;
  staff: string[];
  logoUrl: string | null;
  studentCount: number;
  teacherCount: number;
  establishedYear: number;
  schoolType: string;
  region: string;
  extracurricularActivities: string[];
  affiliations: string[];
  accreditationStatus: string | null;
  country: string;
  city: string;
  postalCode: string;
  socialMediaLinks: Record<string, string> | null;
  lastInspectionDate: string | null;
  totalCampusArea: number;
  numberOfBuildings: number;
  languagesOffered: string[];
  studentTeacherRatio: number;
  schoolLogo: string | null;
  isOnlineLearningAvailable: boolean;
  numberOfClassrooms: number;
  schoolEvents: string[];
  createdAt: string;
  updatedAt: string;
}

export interface CreateSchoolData {
  name: string;
  address: string;
  phoneNumber: string;
  courses?: string[];
  principal: string;
  website?: string | null;
  isActive?: boolean;
  staff?: string[];
  logoUrl?: string | null;
  studentCount?: number;
  teacherCount?: number;
  establishedYear: number;
  schoolType: string;
  region: string;
  extracurricularActivities?: string[];
  affiliations?: string[];
  accreditationStatus?: string | null;
  country: string;
  city: string;
  postalCode: string;
  socialMediaLinks?: Record<string, string> | null;
  lastInspectionDate?: string | null;
  totalCampusArea: number;
  numberOfBuildings: number;
  languagesOffered?: string[];
  studentTeacherRatio: number;
  schoolLogo?: string | null;
  isOnlineLearningAvailable?: boolean;
  numberOfClassrooms: number;
  schoolEvents?: string[];
}
